version: "3.8"
services:
  poc-quarkus-multiple-datasources:
    build:
      context: ../../../
      dockerfile: ./src/main/docker/Dockerfile.dev
    environment:
      - POSTGRESQL_SERVICE_HOST=postgresql
      - POSTGRESQL_SERVICE_PORT=5432
      - MARIADB_SERVICE_HOST=mariadb
      - MARIA_SERVICE_PORT=3306
    ports:
      - 8080:8080
    networks:
      - poc-net
    depends_on:
      - postgresql
      - mariadb
      

  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=postgres
    ports:
        - 5432:5432
    networks:
      - poc-net

        
  mariadb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=ordersdb
      - MYSQL_PASSWORD=maria
      - MYSQL_ROOT_PASSWORD=maria
      - MYSQL_USER=maria
    ports:
        - 3306:3306
    networks:
      - poc-net


networks:
  poc-net:
    driver: bridge
