FROM maven:3.6.3-jdk-11-slim
ENV MVNW_VERBOSE=true
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n"
ENV AB_ENABLED=jmx_exporter

WORKDIR /app
COPY . .
RUN  mvn package

CMD ["/bin/bash", "-c", "/app/mvnw compile quarkus:dev"]
