INSERT INTO USERS (ID, NAME, BIRTH_DATE) VALUES (1, 'John' , CURRENT_DATE);
INSERT INTO USERS (ID, NAME, BIRTH_DATE) VALUES (2, 'Felipe' , CURRENT_DATE);
INSERT INTO USERS (ID, NAME, BIRTH_DATE) VALUES (3, 'Robert', CURRENT_DATE);